# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{inpay}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Wout Fierens"]
  s.date = %q{2011-02-19}
  s.description = %q{An API wrapper for the inpay.com payment system}
  s.email = %q{wout@boysabroad.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "inpay.gemspec",
    "lib/inpay.rb",
    "lib/inpay/checksum.rb",
    "lib/inpay/checksum/create_invoice.rb",
    "lib/inpay/checksum/postback.rb",
    "lib/inpay/config.rb",
    "lib/inpay/core_extensions.rb",
    "lib/inpay/helpers/common.rb",
    "lib/inpay/postback.rb",
    "lib/inpay/rails.rb",
    "lib/inpay/transaction.rb",
    "spec/checksum_spec.rb",
    "spec/inpay_spec.rb",
    "spec/spec_helper.rb",
    "test/helper.rb"
  ]
  s.homepage = %q{http://github.com/wout/inpay}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{An API wrapper for the inpay.com payment system}
  s.test_files = [
    "spec/checksum_spec.rb",
    "spec/inpay_spec.rb",
    "spec/spec_helper.rb",
    "test/helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 2.0.0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 2.0.0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 2.0.0"])
  end
end

